### ISSUE TITLE
Not able to resolve the Validator class

### ISSUE THREAD

**Issue by gaurav2ks** [GinoCanessa/FHIR-CS-Profiling-Basic#1]
`// create a resource validator, which uses our cached resolver
            Validator validator = new Validator(new ValidationSettings()
            {
                ResourceResolver = resolver,
            });`

Seems line Validator class is not available in Hl7.Fhir.Validation namespace anymore, Fire.ly documentation is also missing on profile validations [https://docs.fire.ly/projects/Firely-NET-SDK/validation/profile-validation.html#validating-data-against-profiles]

How to fix this?

**Comment by gaurav2ks** [comment]
Issue is not in the version 3.4.0 of the following packages. 
- hl7.fhir.r4
- hl7.fhir.specification.r4

Issue is there if you are using latest version of these packages. I specifically used 3.4.0 version and code is working fine now.

**Comment by GinoCanessa** [comment]
Thanks! I have it on my to-do list to revisit a lot of the earlier videos to address these types of issues.

**Comment by ytingyeu** [comment]
Just a FYI. Firely has deprecated the old profile validator from `firely-net-sdk` 5.0.0 and moved it to another nuget package `Hl7.Fhir.Validation.Legacy.R4`. The new profile validator for >=5.0.0 is still not available. If you want to use the old validator like in this demo project with the 5.0.0 SDK, you'll need the following nuget packages

```
nuget Hl7.Fhir.R4 >= 5.0.0
nuget Hl7.Fhir.Specification.Data.R4 >= 5.0.0
nuget Hl7.Fhir.Validation.Legacy.R4 >= 5.0.0
```
Replace `R4`  to `STU3`, `R4B`, `R5` if you work on other spec version.

Another thing to notice is,  `Hl7.Fhir.Specification.<release>` now includes both  `Hl7.Fhir.<release>` and `Hl7.Fhir.Specification.Data.<release>` from 5.0.0 so you don't need to reference them all.
